[project]
name = "llm-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.3",
    "tiktoken>=0.9.0",
    "torch>=2.6.0",
    "urllib3>=2.3.0",
]
